/**
 * @fileoverview gRPC-Web generated client stub for wiradata.users
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: users/feature_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var users_feature_message_pb = require('../users/feature_message_pb.js')

var users_generic_message_pb = require('../users/generic_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.users = require('./feature_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.FeatureServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.FeatureServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.MyEmpty,
 *   !proto.wiradata.users.ListFeatureResponse>}
 */
const methodDescriptor_FeatureService_List = new grpc.web.MethodDescriptor(
  '/wiradata.users.FeatureService/List',
  grpc.web.MethodType.SERVER_STREAMING,
  users_generic_message_pb.MyEmpty,
  proto.wiradata.users.ListFeatureResponse,
  /**
   * @param {!proto.wiradata.users.MyEmpty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.users.ListFeatureResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.MyEmpty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListFeatureResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.FeatureServiceClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.FeatureService/List',
      request,
      metadata || {},
      methodDescriptor_FeatureService_List);
};


/**
 * @param {!proto.wiradata.users.MyEmpty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListFeatureResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.FeatureServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.FeatureService/List',
      request,
      metadata || {},
      methodDescriptor_FeatureService_List);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.PackageFeatureServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.PackageFeatureServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.Id,
 *   !proto.wiradata.users.PackageOfFeature>}
 */
const methodDescriptor_PackageFeatureService_View = new grpc.web.MethodDescriptor(
  '/wiradata.users.PackageFeatureService/View',
  grpc.web.MethodType.UNARY,
  users_generic_message_pb.Id,
  users_feature_message_pb.PackageOfFeature,
  /**
   * @param {!proto.wiradata.users.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_feature_message_pb.PackageOfFeature.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.PackageOfFeature)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.PackageOfFeature>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.PackageFeatureServiceClient.prototype.view =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.PackageFeatureService/View',
      request,
      metadata || {},
      methodDescriptor_PackageFeatureService_View,
      callback);
};


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.PackageOfFeature>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.PackageFeatureServicePromiseClient.prototype.view =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.PackageFeatureService/View',
      request,
      metadata || {},
      methodDescriptor_PackageFeatureService_View);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.MyEmpty,
 *   !proto.wiradata.users.ListPackageFeatureResponse>}
 */
const methodDescriptor_PackageFeatureService_List = new grpc.web.MethodDescriptor(
  '/wiradata.users.PackageFeatureService/List',
  grpc.web.MethodType.SERVER_STREAMING,
  users_generic_message_pb.MyEmpty,
  proto.wiradata.users.ListPackageFeatureResponse,
  /**
   * @param {!proto.wiradata.users.MyEmpty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.users.ListPackageFeatureResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.MyEmpty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListPackageFeatureResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.PackageFeatureServiceClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.PackageFeatureService/List',
      request,
      metadata || {},
      methodDescriptor_PackageFeatureService_List);
};


/**
 * @param {!proto.wiradata.users.MyEmpty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListPackageFeatureResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.PackageFeatureServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.PackageFeatureService/List',
      request,
      metadata || {},
      methodDescriptor_PackageFeatureService_List);
};


module.exports = proto.wiradata.users;

