// source: users/feature_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var users_feature_message_pb = require('../users/feature_message_pb.js');
goog.object.extend(proto, users_feature_message_pb);
var users_generic_message_pb = require('../users/generic_message_pb.js');
goog.object.extend(proto, users_generic_message_pb);
goog.exportSymbol('proto.wiradata.users.ListFeatureResponse', null, global);
goog.exportSymbol('proto.wiradata.users.ListPackageFeatureResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wiradata.users.ListFeatureResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wiradata.users.ListFeatureResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wiradata.users.ListFeatureResponse.displayName = 'proto.wiradata.users.ListFeatureResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wiradata.users.ListPackageFeatureResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wiradata.users.ListPackageFeatureResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wiradata.users.ListPackageFeatureResponse.displayName = 'proto.wiradata.users.ListPackageFeatureResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wiradata.users.ListFeatureResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.wiradata.users.ListFeatureResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wiradata.users.ListFeatureResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wiradata.users.ListFeatureResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    feature: (f = msg.getFeature()) && users_feature_message_pb.Feature.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wiradata.users.ListFeatureResponse}
 */
proto.wiradata.users.ListFeatureResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wiradata.users.ListFeatureResponse;
  return proto.wiradata.users.ListFeatureResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wiradata.users.ListFeatureResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wiradata.users.ListFeatureResponse}
 */
proto.wiradata.users.ListFeatureResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new users_feature_message_pb.Feature;
      reader.readMessage(value,users_feature_message_pb.Feature.deserializeBinaryFromReader);
      msg.setFeature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wiradata.users.ListFeatureResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wiradata.users.ListFeatureResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wiradata.users.ListFeatureResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wiradata.users.ListFeatureResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFeature();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      users_feature_message_pb.Feature.serializeBinaryToWriter
    );
  }
};


/**
 * optional Feature feature = 1;
 * @return {?proto.wiradata.users.Feature}
 */
proto.wiradata.users.ListFeatureResponse.prototype.getFeature = function() {
  return /** @type{?proto.wiradata.users.Feature} */ (
    jspb.Message.getWrapperField(this, users_feature_message_pb.Feature, 1));
};


/**
 * @param {?proto.wiradata.users.Feature|undefined} value
 * @return {!proto.wiradata.users.ListFeatureResponse} returns this
*/
proto.wiradata.users.ListFeatureResponse.prototype.setFeature = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wiradata.users.ListFeatureResponse} returns this
 */
proto.wiradata.users.ListFeatureResponse.prototype.clearFeature = function() {
  return this.setFeature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wiradata.users.ListFeatureResponse.prototype.hasFeature = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wiradata.users.ListPackageFeatureResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.wiradata.users.ListPackageFeatureResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wiradata.users.ListPackageFeatureResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wiradata.users.ListPackageFeatureResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    packageOfFeature: (f = msg.getPackageOfFeature()) && users_feature_message_pb.PackageOfFeature.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wiradata.users.ListPackageFeatureResponse}
 */
proto.wiradata.users.ListPackageFeatureResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wiradata.users.ListPackageFeatureResponse;
  return proto.wiradata.users.ListPackageFeatureResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wiradata.users.ListPackageFeatureResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wiradata.users.ListPackageFeatureResponse}
 */
proto.wiradata.users.ListPackageFeatureResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new users_feature_message_pb.PackageOfFeature;
      reader.readMessage(value,users_feature_message_pb.PackageOfFeature.deserializeBinaryFromReader);
      msg.setPackageOfFeature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wiradata.users.ListPackageFeatureResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wiradata.users.ListPackageFeatureResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wiradata.users.ListPackageFeatureResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wiradata.users.ListPackageFeatureResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPackageOfFeature();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      users_feature_message_pb.PackageOfFeature.serializeBinaryToWriter
    );
  }
};


/**
 * optional PackageOfFeature package_of_feature = 1;
 * @return {?proto.wiradata.users.PackageOfFeature}
 */
proto.wiradata.users.ListPackageFeatureResponse.prototype.getPackageOfFeature = function() {
  return /** @type{?proto.wiradata.users.PackageOfFeature} */ (
    jspb.Message.getWrapperField(this, users_feature_message_pb.PackageOfFeature, 1));
};


/**
 * @param {?proto.wiradata.users.PackageOfFeature|undefined} value
 * @return {!proto.wiradata.users.ListPackageFeatureResponse} returns this
*/
proto.wiradata.users.ListPackageFeatureResponse.prototype.setPackageOfFeature = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wiradata.users.ListPackageFeatureResponse} returns this
 */
proto.wiradata.users.ListPackageFeatureResponse.prototype.clearPackageOfFeature = function() {
  return this.setPackageOfFeature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wiradata.users.ListPackageFeatureResponse.prototype.hasPackageOfFeature = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.wiradata.users);
