/**
 * @fileoverview gRPC-Web generated client stub for wiradata.users
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: users/region_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var users_region_message_pb = require('../users/region_message_pb.js')

var users_generic_message_pb = require('../users/generic_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.users = require('./region_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.RegionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.RegionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.Region,
 *   !proto.wiradata.users.Region>}
 */
const methodDescriptor_RegionService_Create = new grpc.web.MethodDescriptor(
  '/wiradata.users.RegionService/Create',
  grpc.web.MethodType.UNARY,
  users_region_message_pb.Region,
  users_region_message_pb.Region,
  /**
   * @param {!proto.wiradata.users.Region} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_region_message_pb.Region.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.Region} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.Region)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.Region>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.RegionService/Create',
      request,
      metadata || {},
      methodDescriptor_RegionService_Create,
      callback);
};


/**
 * @param {!proto.wiradata.users.Region} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.Region>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.RegionServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.RegionService/Create',
      request,
      metadata || {},
      methodDescriptor_RegionService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.Region,
 *   !proto.wiradata.users.Region>}
 */
const methodDescriptor_RegionService_Update = new grpc.web.MethodDescriptor(
  '/wiradata.users.RegionService/Update',
  grpc.web.MethodType.UNARY,
  users_region_message_pb.Region,
  users_region_message_pb.Region,
  /**
   * @param {!proto.wiradata.users.Region} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_region_message_pb.Region.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.Region} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.Region)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.Region>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServiceClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.RegionService/Update',
      request,
      metadata || {},
      methodDescriptor_RegionService_Update,
      callback);
};


/**
 * @param {!proto.wiradata.users.Region} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.Region>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.RegionServicePromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.RegionService/Update',
      request,
      metadata || {},
      methodDescriptor_RegionService_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.Id,
 *   !proto.wiradata.users.Region>}
 */
const methodDescriptor_RegionService_View = new grpc.web.MethodDescriptor(
  '/wiradata.users.RegionService/View',
  grpc.web.MethodType.UNARY,
  users_generic_message_pb.Id,
  users_region_message_pb.Region,
  /**
   * @param {!proto.wiradata.users.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_region_message_pb.Region.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.Region)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.Region>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServiceClient.prototype.view =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.RegionService/View',
      request,
      metadata || {},
      methodDescriptor_RegionService_View,
      callback);
};


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.Region>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.RegionServicePromiseClient.prototype.view =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.RegionService/View',
      request,
      metadata || {},
      methodDescriptor_RegionService_View);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.Id,
 *   !proto.wiradata.users.MyBoolean>}
 */
const methodDescriptor_RegionService_Delete = new grpc.web.MethodDescriptor(
  '/wiradata.users.RegionService/Delete',
  grpc.web.MethodType.UNARY,
  users_generic_message_pb.Id,
  users_generic_message_pb.MyBoolean,
  /**
   * @param {!proto.wiradata.users.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_generic_message_pb.MyBoolean.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.MyBoolean)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.MyBoolean>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.RegionService/Delete',
      request,
      metadata || {},
      methodDescriptor_RegionService_Delete,
      callback);
};


/**
 * @param {!proto.wiradata.users.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.MyBoolean>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.RegionServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.RegionService/Delete',
      request,
      metadata || {},
      methodDescriptor_RegionService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.ListRegionRequest,
 *   !proto.wiradata.users.ListRegionResponse>}
 */
const methodDescriptor_RegionService_List = new grpc.web.MethodDescriptor(
  '/wiradata.users.RegionService/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.wiradata.users.ListRegionRequest,
  proto.wiradata.users.ListRegionResponse,
  /**
   * @param {!proto.wiradata.users.ListRegionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.users.ListRegionResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.ListRegionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListRegionResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServiceClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.RegionService/List',
      request,
      metadata || {},
      methodDescriptor_RegionService_List);
};


/**
 * @param {!proto.wiradata.users.ListRegionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListRegionResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.RegionServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.users.RegionService/List',
      request,
      metadata || {},
      methodDescriptor_RegionService_List);
};


module.exports = proto.wiradata.users;

