/**
 * @fileoverview gRPC-Web generated client stub for wiradata.inventories
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: inventories/warehouse_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var inventories_warehouse_message_pb = require('../inventories/warehouse_message_pb.js')

var inventories_generic_message_pb = require('../inventories/generic_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.inventories = require('./warehouse_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.WarehouseServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.WarehouseServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Warehouse,
 *   !proto.wiradata.inventories.Warehouse>}
 */
const methodDescriptor_WarehouseService_Create = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.WarehouseService/Create',
  grpc.web.MethodType.UNARY,
  inventories_warehouse_message_pb.Warehouse,
  inventories_warehouse_message_pb.Warehouse,
  /**
   * @param {!proto.wiradata.inventories.Warehouse} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_warehouse_message_pb.Warehouse.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Warehouse} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Warehouse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Warehouse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Create',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Create,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Warehouse} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Warehouse>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.WarehouseServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Create',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Warehouse,
 *   !proto.wiradata.inventories.Warehouse>}
 */
const methodDescriptor_WarehouseService_Update = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.WarehouseService/Update',
  grpc.web.MethodType.UNARY,
  inventories_warehouse_message_pb.Warehouse,
  inventories_warehouse_message_pb.Warehouse,
  /**
   * @param {!proto.wiradata.inventories.Warehouse} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_warehouse_message_pb.Warehouse.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Warehouse} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Warehouse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Warehouse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServiceClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Update',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Update,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Warehouse} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Warehouse>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.WarehouseServicePromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Update',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Id,
 *   !proto.wiradata.inventories.Warehouse>}
 */
const methodDescriptor_WarehouseService_View = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.WarehouseService/View',
  grpc.web.MethodType.UNARY,
  inventories_generic_message_pb.Id,
  inventories_warehouse_message_pb.Warehouse,
  /**
   * @param {!proto.wiradata.inventories.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_warehouse_message_pb.Warehouse.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Warehouse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Warehouse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServiceClient.prototype.view =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/View',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_View,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Warehouse>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.WarehouseServicePromiseClient.prototype.view =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/View',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_View);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Id,
 *   !proto.wiradata.inventories.MyBoolean>}
 */
const methodDescriptor_WarehouseService_Delete = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.WarehouseService/Delete',
  grpc.web.MethodType.UNARY,
  inventories_generic_message_pb.Id,
  inventories_generic_message_pb.MyBoolean,
  /**
   * @param {!proto.wiradata.inventories.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_generic_message_pb.MyBoolean.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.MyBoolean)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.MyBoolean>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Delete',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Delete,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.MyBoolean>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.WarehouseServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.WarehouseService/Delete',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.ListWarehouseRequest,
 *   !proto.wiradata.inventories.ListWarehouseResponse>}
 */
const methodDescriptor_WarehouseService_List = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.WarehouseService/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.wiradata.inventories.ListWarehouseRequest,
  proto.wiradata.inventories.ListWarehouseResponse,
  /**
   * @param {!proto.wiradata.inventories.ListWarehouseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.inventories.ListWarehouseResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.ListWarehouseRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.ListWarehouseResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServiceClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.inventories.WarehouseService/List',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_List);
};


/**
 * @param {!proto.wiradata.inventories.ListWarehouseRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.ListWarehouseResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.WarehouseServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.inventories.WarehouseService/List',
      request,
      metadata || {},
      methodDescriptor_WarehouseService_List);
};


module.exports = proto.wiradata.inventories;

