/**
 * @fileoverview gRPC-Web generated client stub for sales
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: sales/sales_return_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var sales_sales_return_message_pb = require('../sales/sales_return_message_pb.js')

var sales_generic_message_pb = require('../sales/generic_message_pb.js')
const proto = {};
proto.sales = require('./sales_return_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sales.SalesReturnServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sales.SalesReturnServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sales.SalesReturn,
 *   !proto.sales.SalesReturn>}
 */
const methodDescriptor_SalesReturnService_SalesReturnCreate = new grpc.web.MethodDescriptor(
  '/sales.SalesReturnService/SalesReturnCreate',
  grpc.web.MethodType.UNARY,
  sales_sales_return_message_pb.SalesReturn,
  sales_sales_return_message_pb.SalesReturn,
  /**
   * @param {!proto.sales.SalesReturn} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  sales_sales_return_message_pb.SalesReturn.deserializeBinary
);


/**
 * @param {!proto.sales.SalesReturn} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sales.SalesReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sales.SalesReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sales.SalesReturnServiceClient.prototype.salesReturnCreate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnCreate',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnCreate,
      callback);
};


/**
 * @param {!proto.sales.SalesReturn} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sales.SalesReturn>}
 *     Promise that resolves to the response
 */
proto.sales.SalesReturnServicePromiseClient.prototype.salesReturnCreate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnCreate',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnCreate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sales.SalesReturn,
 *   !proto.sales.SalesReturn>}
 */
const methodDescriptor_SalesReturnService_SalesReturnUpdate = new grpc.web.MethodDescriptor(
  '/sales.SalesReturnService/SalesReturnUpdate',
  grpc.web.MethodType.UNARY,
  sales_sales_return_message_pb.SalesReturn,
  sales_sales_return_message_pb.SalesReturn,
  /**
   * @param {!proto.sales.SalesReturn} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  sales_sales_return_message_pb.SalesReturn.deserializeBinary
);


/**
 * @param {!proto.sales.SalesReturn} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sales.SalesReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sales.SalesReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sales.SalesReturnServiceClient.prototype.salesReturnUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnUpdate',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnUpdate,
      callback);
};


/**
 * @param {!proto.sales.SalesReturn} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sales.SalesReturn>}
 *     Promise that resolves to the response
 */
proto.sales.SalesReturnServicePromiseClient.prototype.salesReturnUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnUpdate',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sales.Id,
 *   !proto.sales.SalesReturn>}
 */
const methodDescriptor_SalesReturnService_SalesReturnView = new grpc.web.MethodDescriptor(
  '/sales.SalesReturnService/SalesReturnView',
  grpc.web.MethodType.UNARY,
  sales_generic_message_pb.Id,
  sales_sales_return_message_pb.SalesReturn,
  /**
   * @param {!proto.sales.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  sales_sales_return_message_pb.SalesReturn.deserializeBinary
);


/**
 * @param {!proto.sales.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sales.SalesReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sales.SalesReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sales.SalesReturnServiceClient.prototype.salesReturnView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnView',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnView,
      callback);
};


/**
 * @param {!proto.sales.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sales.SalesReturn>}
 *     Promise that resolves to the response
 */
proto.sales.SalesReturnServicePromiseClient.prototype.salesReturnView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnView',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sales.ListSalesReturnRequest,
 *   !proto.sales.ListSalesReturnResponse>}
 */
const methodDescriptor_SalesReturnService_SalesReturnList = new grpc.web.MethodDescriptor(
  '/sales.SalesReturnService/SalesReturnList',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.sales.ListSalesReturnRequest,
  proto.sales.ListSalesReturnResponse,
  /**
   * @param {!proto.sales.ListSalesReturnRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sales.ListSalesReturnResponse.deserializeBinary
);


/**
 * @param {!proto.sales.ListSalesReturnRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sales.ListSalesReturnResponse>}
 *     The XHR Node Readable Stream
 */
proto.sales.SalesReturnServiceClient.prototype.salesReturnList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnList',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnList);
};


/**
 * @param {!proto.sales.ListSalesReturnRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sales.ListSalesReturnResponse>}
 *     The XHR Node Readable Stream
 */
proto.sales.SalesReturnServicePromiseClient.prototype.salesReturnList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sales.SalesReturnService/SalesReturnList',
      request,
      metadata || {},
      methodDescriptor_SalesReturnService_SalesReturnList);
};


module.exports = proto.sales;

