// source: purchases/purchase_return_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var purchases_purchase_message_pb = require('../purchases/purchase_message_pb.js');
goog.object.extend(proto, purchases_purchase_message_pb);
goog.exportSymbol('proto.purchases.PurchaseReturn', null, global);
goog.exportSymbol('proto.purchases.PurchaseReturnDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.purchases.PurchaseReturn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.purchases.PurchaseReturn.repeatedFields_, null);
};
goog.inherits(proto.purchases.PurchaseReturn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.purchases.PurchaseReturn.displayName = 'proto.purchases.PurchaseReturn';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.purchases.PurchaseReturnDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.purchases.PurchaseReturnDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.purchases.PurchaseReturnDetail.displayName = 'proto.purchases.PurchaseReturnDetail';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.purchases.PurchaseReturn.repeatedFields_ = [16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.purchases.PurchaseReturn.prototype.toObject = function(opt_includeInstance) {
  return proto.purchases.PurchaseReturn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.purchases.PurchaseReturn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.purchases.PurchaseReturn.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    branchId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    branchName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    purchase: (f = msg.getPurchase()) && purchases_purchase_message_pb.Purchase.toObject(includeInstance, f),
    code: jspb.Message.getFieldWithDefault(msg, 5, ""),
    returnDate: jspb.Message.getFieldWithDefault(msg, 6, ""),
    remark: jspb.Message.getFieldWithDefault(msg, 7, ""),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    additionalDiscAmount: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    additionalDiscPercentage: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    totalPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 12, ""),
    createdBy: jspb.Message.getFieldWithDefault(msg, 13, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 14, ""),
    updatedBy: jspb.Message.getFieldWithDefault(msg, 15, ""),
    detailsList: jspb.Message.toObjectList(msg.getDetailsList(),
    proto.purchases.PurchaseReturnDetail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.purchases.PurchaseReturn}
 */
proto.purchases.PurchaseReturn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.purchases.PurchaseReturn;
  return proto.purchases.PurchaseReturn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.purchases.PurchaseReturn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.purchases.PurchaseReturn}
 */
proto.purchases.PurchaseReturn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBranchId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBranchName(value);
      break;
    case 4:
      var value = new purchases_purchase_message_pb.Purchase;
      reader.readMessage(value,purchases_purchase_message_pb.Purchase.deserializeBinaryFromReader);
      msg.setPurchase(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setReturnDate(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemark(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAdditionalDiscAmount(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAdditionalDiscPercentage(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalPrice(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedBy(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedBy(value);
      break;
    case 16:
      var value = new proto.purchases.PurchaseReturnDetail;
      reader.readMessage(value,proto.purchases.PurchaseReturnDetail.deserializeBinaryFromReader);
      msg.addDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.purchases.PurchaseReturn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.purchases.PurchaseReturn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.purchases.PurchaseReturn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.purchases.PurchaseReturn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBranchId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBranchName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPurchase();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      purchases_purchase_message_pb.Purchase.serializeBinaryToWriter
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getReturnDate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRemark();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getAdditionalDiscAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getAdditionalDiscPercentage();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getTotalPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCreatedBy();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getUpdatedBy();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getDetailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      proto.purchases.PurchaseReturnDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string branch_id = 2;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getBranchId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setBranchId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string branch_name = 3;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getBranchName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setBranchName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Purchase Purchase = 4;
 * @return {?proto.purchases.Purchase}
 */
proto.purchases.PurchaseReturn.prototype.getPurchase = function() {
  return /** @type{?proto.purchases.Purchase} */ (
    jspb.Message.getWrapperField(this, purchases_purchase_message_pb.Purchase, 4));
};


/**
 * @param {?proto.purchases.Purchase|undefined} value
 * @return {!proto.purchases.PurchaseReturn} returns this
*/
proto.purchases.PurchaseReturn.prototype.setPurchase = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.clearPurchase = function() {
  return this.setPurchase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.purchases.PurchaseReturn.prototype.hasPurchase = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string code = 5;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string return_date = 6;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getReturnDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setReturnDate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string remark = 7;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getRemark = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setRemark = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional double price = 8;
 * @return {number}
 */
proto.purchases.PurchaseReturn.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double additional_disc_amount = 9;
 * @return {number}
 */
proto.purchases.PurchaseReturn.prototype.getAdditionalDiscAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setAdditionalDiscAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional float additional_disc_percentage = 10;
 * @return {number}
 */
proto.purchases.PurchaseReturn.prototype.getAdditionalDiscPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setAdditionalDiscPercentage = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double total_price = 11;
 * @return {number}
 */
proto.purchases.PurchaseReturn.prototype.getTotalPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setTotalPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional string created_at = 12;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string created_by = 13;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getCreatedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setCreatedBy = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string updated_at = 14;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string updated_by = 15;
 * @return {string}
 */
proto.purchases.PurchaseReturn.prototype.getUpdatedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.setUpdatedBy = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * repeated PurchaseReturnDetail details = 16;
 * @return {!Array<!proto.purchases.PurchaseReturnDetail>}
 */
proto.purchases.PurchaseReturn.prototype.getDetailsList = function() {
  return /** @type{!Array<!proto.purchases.PurchaseReturnDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.purchases.PurchaseReturnDetail, 16));
};


/**
 * @param {!Array<!proto.purchases.PurchaseReturnDetail>} value
 * @return {!proto.purchases.PurchaseReturn} returns this
*/
proto.purchases.PurchaseReturn.prototype.setDetailsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.purchases.PurchaseReturnDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.purchases.PurchaseReturnDetail}
 */
proto.purchases.PurchaseReturn.prototype.addDetails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.purchases.PurchaseReturnDetail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.purchases.PurchaseReturn} returns this
 */
proto.purchases.PurchaseReturn.prototype.clearDetailsList = function() {
  return this.setDetailsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.purchases.PurchaseReturnDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.purchases.PurchaseReturnDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.purchases.PurchaseReturnDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.purchases.PurchaseReturnDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purchaseReturnId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    productId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    productCode: jspb.Message.getFieldWithDefault(msg, 4, ""),
    productName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    quantity: jspb.Message.getFieldWithDefault(msg, 6, 0),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    discAmount: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    discPercentage: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    totalPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.purchases.PurchaseReturnDetail}
 */
proto.purchases.PurchaseReturnDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.purchases.PurchaseReturnDetail;
  return proto.purchases.PurchaseReturnDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.purchases.PurchaseReturnDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.purchases.PurchaseReturnDetail}
 */
proto.purchases.PurchaseReturnDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurchaseReturnId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductCode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductName(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDiscAmount(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDiscPercentage(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalPrice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.purchases.PurchaseReturnDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.purchases.PurchaseReturnDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.purchases.PurchaseReturnDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.purchases.PurchaseReturnDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurchaseReturnId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProductCode();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProductName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getDiscAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getDiscPercentage();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getTotalPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.purchases.PurchaseReturnDetail.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string purchase_return_id = 2;
 * @return {string}
 */
proto.purchases.PurchaseReturnDetail.prototype.getPurchaseReturnId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setPurchaseReturnId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string product_id = 3;
 * @return {string}
 */
proto.purchases.PurchaseReturnDetail.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string product_code = 4;
 * @return {string}
 */
proto.purchases.PurchaseReturnDetail.prototype.getProductCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setProductCode = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string product_name = 5;
 * @return {string}
 */
proto.purchases.PurchaseReturnDetail.prototype.getProductName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setProductName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 quantity = 6;
 * @return {number}
 */
proto.purchases.PurchaseReturnDetail.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional double price = 7;
 * @return {number}
 */
proto.purchases.PurchaseReturnDetail.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double disc_amount = 8;
 * @return {number}
 */
proto.purchases.PurchaseReturnDetail.prototype.getDiscAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setDiscAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float disc_percentage = 9;
 * @return {number}
 */
proto.purchases.PurchaseReturnDetail.prototype.getDiscPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setDiscPercentage = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double total_price = 10;
 * @return {number}
 */
proto.purchases.PurchaseReturnDetail.prototype.getTotalPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.purchases.PurchaseReturnDetail} returns this
 */
proto.purchases.PurchaseReturnDetail.prototype.setTotalPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


goog.object.extend(exports, proto.purchases);
