/**
 * @fileoverview gRPC-Web generated client stub for purchases
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: purchases/purchase_return_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var purchases_purchase_return_message_pb = require('../purchases/purchase_return_message_pb.js')

var purchases_generic_message_pb = require('../purchases/generic_message_pb.js')
const proto = {};
proto.purchases = require('./purchase_return_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.purchases.PurchaseReturnServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.purchases.PurchaseReturnServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.purchases.PurchaseReturn,
 *   !proto.purchases.PurchaseReturn>}
 */
const methodDescriptor_PurchaseReturnService_PurchaseReturnCreate = new grpc.web.MethodDescriptor(
  '/purchases.PurchaseReturnService/PurchaseReturnCreate',
  grpc.web.MethodType.UNARY,
  purchases_purchase_return_message_pb.PurchaseReturn,
  purchases_purchase_return_message_pb.PurchaseReturn,
  /**
   * @param {!proto.purchases.PurchaseReturn} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  purchases_purchase_return_message_pb.PurchaseReturn.deserializeBinary
);


/**
 * @param {!proto.purchases.PurchaseReturn} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.purchases.PurchaseReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.purchases.PurchaseReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.purchases.PurchaseReturnServiceClient.prototype.purchaseReturnCreate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnCreate',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnCreate,
      callback);
};


/**
 * @param {!proto.purchases.PurchaseReturn} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.purchases.PurchaseReturn>}
 *     Promise that resolves to the response
 */
proto.purchases.PurchaseReturnServicePromiseClient.prototype.purchaseReturnCreate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnCreate',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnCreate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.purchases.PurchaseReturn,
 *   !proto.purchases.PurchaseReturn>}
 */
const methodDescriptor_PurchaseReturnService_PurchaseReturnUpdate = new grpc.web.MethodDescriptor(
  '/purchases.PurchaseReturnService/PurchaseReturnUpdate',
  grpc.web.MethodType.UNARY,
  purchases_purchase_return_message_pb.PurchaseReturn,
  purchases_purchase_return_message_pb.PurchaseReturn,
  /**
   * @param {!proto.purchases.PurchaseReturn} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  purchases_purchase_return_message_pb.PurchaseReturn.deserializeBinary
);


/**
 * @param {!proto.purchases.PurchaseReturn} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.purchases.PurchaseReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.purchases.PurchaseReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.purchases.PurchaseReturnServiceClient.prototype.purchaseReturnUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnUpdate',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnUpdate,
      callback);
};


/**
 * @param {!proto.purchases.PurchaseReturn} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.purchases.PurchaseReturn>}
 *     Promise that resolves to the response
 */
proto.purchases.PurchaseReturnServicePromiseClient.prototype.purchaseReturnUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnUpdate',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.purchases.Id,
 *   !proto.purchases.PurchaseReturn>}
 */
const methodDescriptor_PurchaseReturnService_PurchaseReturnView = new grpc.web.MethodDescriptor(
  '/purchases.PurchaseReturnService/PurchaseReturnView',
  grpc.web.MethodType.UNARY,
  purchases_generic_message_pb.Id,
  purchases_purchase_return_message_pb.PurchaseReturn,
  /**
   * @param {!proto.purchases.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  purchases_purchase_return_message_pb.PurchaseReturn.deserializeBinary
);


/**
 * @param {!proto.purchases.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.purchases.PurchaseReturn)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.purchases.PurchaseReturn>|undefined}
 *     The XHR Node Readable Stream
 */
proto.purchases.PurchaseReturnServiceClient.prototype.purchaseReturnView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnView',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnView,
      callback);
};


/**
 * @param {!proto.purchases.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.purchases.PurchaseReturn>}
 *     Promise that resolves to the response
 */
proto.purchases.PurchaseReturnServicePromiseClient.prototype.purchaseReturnView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnView',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.purchases.ListPurchaseReturnRequest,
 *   !proto.purchases.ListPurchaseReturnResponse>}
 */
const methodDescriptor_PurchaseReturnService_PurchaseReturnList = new grpc.web.MethodDescriptor(
  '/purchases.PurchaseReturnService/PurchaseReturnList',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.purchases.ListPurchaseReturnRequest,
  proto.purchases.ListPurchaseReturnResponse,
  /**
   * @param {!proto.purchases.ListPurchaseReturnRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.purchases.ListPurchaseReturnResponse.deserializeBinary
);


/**
 * @param {!proto.purchases.ListPurchaseReturnRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.purchases.ListPurchaseReturnResponse>}
 *     The XHR Node Readable Stream
 */
proto.purchases.PurchaseReturnServiceClient.prototype.purchaseReturnList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnList',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnList);
};


/**
 * @param {!proto.purchases.ListPurchaseReturnRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.purchases.ListPurchaseReturnResponse>}
 *     The XHR Node Readable Stream
 */
proto.purchases.PurchaseReturnServicePromiseClient.prototype.purchaseReturnList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/purchases.PurchaseReturnService/PurchaseReturnList',
      request,
      metadata || {},
      methodDescriptor_PurchaseReturnService_PurchaseReturnList);
};


module.exports = proto.purchases;

