/**
 * @fileoverview gRPC-Web generated client stub for wiradata.users
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: users/access_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var users_access_message_pb = require('../users/access_message_pb.js')

var users_generic_message_pb = require('../users/generic_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.users = require('./access_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.AccessServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.users.AccessServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.users.MyEmpty,
 *   !proto.wiradata.users.ListAccessResponse>}
 */
const methodDescriptor_AccessService_List = new grpc.web.MethodDescriptor(
  '/wiradata.users.AccessService/List',
  grpc.web.MethodType.UNARY,
  users_generic_message_pb.MyEmpty,
  users_access_message_pb.ListAccessResponse,
  /**
   * @param {!proto.wiradata.users.MyEmpty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  users_access_message_pb.ListAccessResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.users.MyEmpty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.users.ListAccessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.users.ListAccessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.users.AccessServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.users.AccessService/List',
      request,
      metadata || {},
      methodDescriptor_AccessService_List,
      callback);
};


/**
 * @param {!proto.wiradata.users.MyEmpty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.users.ListAccessResponse>}
 *     Promise that resolves to the response
 */
proto.wiradata.users.AccessServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.users.AccessService/List',
      request,
      metadata || {},
      methodDescriptor_AccessService_List);
};


module.exports = proto.wiradata.users;

