/**
 * @fileoverview gRPC-Web generated client stub for wiradata.inventories
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: inventories/receive_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var inventories_receive_message_pb = require('../inventories/receive_message_pb.js')

var inventories_generic_message_pb = require('../inventories/generic_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.inventories = require('./receive_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.ReceiveServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.ReceiveServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Receive,
 *   !proto.wiradata.inventories.Receive>}
 */
const methodDescriptor_ReceiveService_Create = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.ReceiveService/Create',
  grpc.web.MethodType.UNARY,
  inventories_receive_message_pb.Receive,
  inventories_receive_message_pb.Receive,
  /**
   * @param {!proto.wiradata.inventories.Receive} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_receive_message_pb.Receive.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Receive} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Receive)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Receive>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.ReceiveServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/Create',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_Create,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Receive} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Receive>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.ReceiveServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/Create',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Receive,
 *   !proto.wiradata.inventories.Receive>}
 */
const methodDescriptor_ReceiveService_Update = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.ReceiveService/Update',
  grpc.web.MethodType.UNARY,
  inventories_receive_message_pb.Receive,
  inventories_receive_message_pb.Receive,
  /**
   * @param {!proto.wiradata.inventories.Receive} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_receive_message_pb.Receive.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Receive} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Receive)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Receive>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.ReceiveServiceClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/Update',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_Update,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Receive} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Receive>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.ReceiveServicePromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/Update',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.Id,
 *   !proto.wiradata.inventories.Receive>}
 */
const methodDescriptor_ReceiveService_View = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.ReceiveService/View',
  grpc.web.MethodType.UNARY,
  inventories_generic_message_pb.Id,
  inventories_receive_message_pb.Receive,
  /**
   * @param {!proto.wiradata.inventories.Id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_receive_message_pb.Receive.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.Receive)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.Receive>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.ReceiveServiceClient.prototype.view =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/View',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_View,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.Id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.Receive>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.ReceiveServicePromiseClient.prototype.view =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.ReceiveService/View',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_View);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.ListReceiveRequest,
 *   !proto.wiradata.inventories.ListReceiveResponse>}
 */
const methodDescriptor_ReceiveService_List = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.ReceiveService/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.wiradata.inventories.ListReceiveRequest,
  proto.wiradata.inventories.ListReceiveResponse,
  /**
   * @param {!proto.wiradata.inventories.ListReceiveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.inventories.ListReceiveResponse.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.ListReceiveRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.ListReceiveResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.ReceiveServiceClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.inventories.ReceiveService/List',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_List);
};


/**
 * @param {!proto.wiradata.inventories.ListReceiveRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.ListReceiveResponse>}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.ReceiveServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/wiradata.inventories.ReceiveService/List',
      request,
      metadata || {},
      methodDescriptor_ReceiveService_List);
};


module.exports = proto.wiradata.inventories;

