/**
 * @fileoverview gRPC-Web generated client stub for wiradata.inventories
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: inventories/stock_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var inventories_generic_message_pb = require('../inventories/generic_message_pb.js')

var inventories_product_message_pb = require('../inventories/product_message_pb.js')
const proto = {};
proto.wiradata = {};
proto.wiradata.inventories = require('./stock_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.StockServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wiradata.inventories.StockServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.ClosingStockRequest,
 *   !proto.wiradata.inventories.MyBoolean>}
 */
const methodDescriptor_StockService_Closing = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.StockService/Closing',
  grpc.web.MethodType.UNARY,
  proto.wiradata.inventories.ClosingStockRequest,
  inventories_generic_message_pb.MyBoolean,
  /**
   * @param {!proto.wiradata.inventories.ClosingStockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  inventories_generic_message_pb.MyBoolean.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.ClosingStockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.MyBoolean)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.MyBoolean>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.StockServiceClient.prototype.closing =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.StockService/Closing',
      request,
      metadata || {},
      methodDescriptor_StockService_Closing,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.ClosingStockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.MyBoolean>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.StockServicePromiseClient.prototype.closing =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.StockService/Closing',
      request,
      metadata || {},
      methodDescriptor_StockService_Closing);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.StockListInput,
 *   !proto.wiradata.inventories.StockList>}
 */
const methodDescriptor_StockService_List = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.StockService/List',
  grpc.web.MethodType.UNARY,
  proto.wiradata.inventories.StockListInput,
  proto.wiradata.inventories.StockList,
  /**
   * @param {!proto.wiradata.inventories.StockListInput} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.inventories.StockList.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.StockListInput} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.StockList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.StockList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.StockServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.StockService/List',
      request,
      metadata || {},
      methodDescriptor_StockService_List,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.StockListInput} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.StockList>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.StockServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.StockService/List',
      request,
      metadata || {},
      methodDescriptor_StockService_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wiradata.inventories.StockInfoInput,
 *   !proto.wiradata.inventories.StockInfo>}
 */
const methodDescriptor_StockService_Info = new grpc.web.MethodDescriptor(
  '/wiradata.inventories.StockService/Info',
  grpc.web.MethodType.UNARY,
  proto.wiradata.inventories.StockInfoInput,
  proto.wiradata.inventories.StockInfo,
  /**
   * @param {!proto.wiradata.inventories.StockInfoInput} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wiradata.inventories.StockInfo.deserializeBinary
);


/**
 * @param {!proto.wiradata.inventories.StockInfoInput} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wiradata.inventories.StockInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wiradata.inventories.StockInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wiradata.inventories.StockServiceClient.prototype.info =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wiradata.inventories.StockService/Info',
      request,
      metadata || {},
      methodDescriptor_StockService_Info,
      callback);
};


/**
 * @param {!proto.wiradata.inventories.StockInfoInput} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wiradata.inventories.StockInfo>}
 *     Promise that resolves to the response
 */
proto.wiradata.inventories.StockServicePromiseClient.prototype.info =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wiradata.inventories.StockService/Info',
      request,
      metadata || {},
      methodDescriptor_StockService_Info);
};


module.exports = proto.wiradata.inventories;

